import { useRef, useState } from "react";
import Head from "next/head";
import {
  RichTextEditorComponent,
  Toolbar,
  Link,
  Inject,
  HtmlEditor,
  Table,
  PasteCleanup,
  PasteCleanupSettingsModel,
} from "@syncfusion/ej2-react-richtexteditor";

import styles from "../styles/Home.module.css";

const toolbarSettings = {
  items: [
    "Bold",
    "Italic",
    "Underline",
    "StrikeThrough",
    "|",
    "CreateLink",
    "|",
    "SubScript",
    "SuperScript",
    "|",
    "Outdent",
    "Indent",
    "OrderedList",
    "UnorderedList",
    "|",
    "CreateTable",
    "|",
    "SourceCode",
  ],
};

const pasteCleanupSettings: PasteCleanupSettingsModel = {
  prompt: false,
  deniedAttrs: [],
  // allowedStyleProps,
  // deniedTags: blocklistTags,
  keepFormat: true,
  plainText: false,
};

const initText = `<p>Try to change the format of one of these words to reproduce the issue.</p><ul><li><span class="e-editor-select-start">It works with dev server</span></li><li>It works with built server if 'swcMinify: false'</li><li>It does not work with built server&nbsp;<span style="color: rgb(51, 51, 51); font-family: Roboto, &quot;Segoe UI&quot;, GeezaPro, &quot;DejaVu Serif&quot;, &quot;sans-serif&quot;, -apple-system, BlinkMacSystemFont; font-size: 14px; font-style: normal; font-weight: 400; text-align: left; text-indent: 0px; white-space: normal; background-color: rgb(255, 255, 255); display: inline !important; float: none;">if 'swcMinify: true'</span></li></ul><p>​</p>`;

export default function Home() {
  const [value, setValue] = useState(initText);
  const rteRef: any = useRef(null);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h4 className={styles.title}>
          Syncfusion RichTextEditor vs swcMinify: true
        </h4>

        <br />
        <br />

        <RichTextEditorComponent
          ref={rteRef}
          value={value}
          toolbarSettings={toolbarSettings}
          pasteCleanupSettings={pasteCleanupSettings}
          enableResize={false}
        >
          <Inject services={[Toolbar, Link, HtmlEditor, Table, PasteCleanup]} />
        </RichTextEditorComponent>
      </main>
    </div>
  );
}
